name: Update tournaments

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-tournaments:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5

      # Set up and run python script
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r _scripts/requirements.txt
      - name: Run script
        run: |
          python _scripts/update_tournaments.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update tournaments
          file_pattern: '*.tsv'
