name: Data syntax

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        run: |
          yamllint -d "{extends: relaxed, rules: {trailing-spaces: {level: warning}, new-line-at-end-of-file: {level: warning}}}" _data/

  validate-tsv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: csvlinter
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.tsv"
          find_path: "_data"
          extra_params: "--delimiter=\t"
